### PR TITLE
Add section about text editor settings

### PR DESCRIPTION
**Pull request by markburns**
When adding better_errors to a new project I couldn't remember how this was done.
I think this setting would be useful to make more visible.

### CODE REVIEW

**Comment by arthurnn** [comment]
didnt know about this.
this is cool.
:shipit:

**Comment by markburns** [comment]
Is this a controversial change? Doesn't seem useful? I had to remind myself of this again on a new project.

**Comment by rstacruz** [comment]
Just forgotten... sorry about that!

**Comment by markburns** [comment]
No worries, just checking!

**Pull request merged**
