### PR TITLE
Use cause instead of original_exception

### PR DESCRIPTION
**Pull request by wavedocs**

### CODE REVIEW

**Comment by connorshea** [comment]
:+1: I'm running into this deprecation warning on Rails 5 with `better_errors`.

```
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/connor/.rvm/gems/ruby-2.3.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:7)
DEPRECATION WARNING: #original_exception is deprecated. Use #cause instead. (called from initialize at /Users/connor/.rvm/gems/ruby-2.3.0/gems/better_errors-2.1.1/lib/better_errors/raised_exception.rb:8)
```

**Comment by Empact** [comment]
#325 also fixes this

**Comment by dg-ratiodata** [comment]
@charliesome Did you find the time to review this?

**Comment by sreuterle** [comment]
Will there be a new version of this Gem with full compatibility to Rails 5 in near future? Or is there any alternative which is currently maintained?

**Comment by RobinDaugherty** [comment]
Thanks for your help! This was fixed in release 2.2.0 by #354.

**Pull request closed without merging**
