### PR TITLE
Fix browser performance issues with configurable maximum variable size

### LINKED ISSUE #334: Large /variables request
I'm seeing very slow performance when using better errors. Looking in the console I see the XHR request to /variables is over 80MB and it takes ages to render.

I have tried adding the following which helps on some pages but not all:

```
if defined?(BetterErrors) && Rails.env.development?
  BetterErrors.ignored_instance_variables += [ :@_request, :@_assigns, :@_controller, :@ahoy, :@view_renderer ]
end
```

Is this a better errors issue or is there a configuration setting somewhere to reduce the amount of info displayed?

### PR DESCRIPTION
**Pull request by bquorning**
Based on my comment on #334 and @tobypinder’s PR #360:

> this will allow the user to set a maximum payload size for `variable.inspect`, above which the variable is filtered out of the error page. This solves many performance problems associated with the browser being slow to render error pages, the CPU requirements for the error page skyrocketing etc.
> 
> Many variable types end up being huge like Rails collections being inspected (and therefore queried for) before they are paginated. I've set the default to 100,000 characters, but the default can be modified to unlimited by setting `BetterErrors.maximum_variable_inspect_size` to `nil`, if we think compatibility is more important than a friendly default.

Closes #360 
Closes #334

### CODE REVIEW

**Comment by RobinDaugherty** [comment]
The tests are going to need some work. Looks like the new functionality will only work with binding_of_caller, which makes sense. I recently merged changes that make the binding_of_caller-dependent specs run selectively, so this is failing in CI because it's not in the right context. I'll take a look at the specs.

**Comment by seanlinsley** [comment]
This prevents the browser from having to deal with rendering the content, but in my case 17 seconds are still spent calling `inspect` only to throw away its value.

**Comment by seanlinsley** [comment]
Perhaps we could make use of `ObjectSpace.memsize_of` for applications using MRI.

**Comment by RobinDaugherty** [comment]
That's a great idea @seanlinsley. I've opened #412 so we don't lose track of it.

**Pull request merged**
